-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-23 19:51:15 SGT
--   site:      DB2/UDB 7.1
--   type:      DB2/UDB 7.1



CREATE TABLE Dosen 
    (
     NIP CHAR (18) NOT NULL , 
     Nama VARCHAR (35) NOT NULL , 
     Alamat VARCHAR (50) NOT NULL , 
     No_Hp VARCHAR (15) NOT NULL , 
     Email VARCHAR (30) NOT NULL , 
     Prodi_Kode_Prodi CHAR (5) NOT NULL , 
     Dosen_NIP CHAR (18) 
    )
;

ALTER TABLE Dosen ADD CONSTRAINT Dosen_PK PRIMARY KEY (NIP)
;

CREATE TABLE Fakultas 
    (
     Kode_Fakultas CHAR (2) NOT NULL , 
     Nama_Fakultas VARCHAR (30) NOT NULL 
    )
;

ALTER TABLE Fakultas ADD CONSTRAINT Fakultas_PK PRIMARY KEY (Kode_Fakultas)
;

CREATE TABLE KRS 
    (
     Kode_KRS CHAR (5) NOT NULL , 
     Jumlah_SKS INTEGER NOT NULL , 
     Mahasiswa_NIM CHAR (10) NOT NULL , 
     Mata_Kuliah_Kode_MK CHAR (12) NOT NULL 
    )
;

ALTER TABLE KRS ADD CONSTRAINT KRS_PK PRIMARY KEY (Kode_KRS)
;

CREATE TABLE Mahasiswa 
    (
     NIM CHAR (10) NOT NULL , 
     Nama VARCHAR (35) NOT NULL , 
     Alamat VARCHAR (50) NOT NULL , 
     No_Hp VARCHAR (15) NOT NULL , 
     Email VARCHAR (30) NOT NULL , 
     Prodi_Kode_Prodi CHAR (5) NOT NULL 
    )
;

ALTER TABLE Mahasiswa ADD CONSTRAINT Mahasiswa_PK PRIMARY KEY (NIM)
;

CREATE TABLE Mata_Kuliah 
    (
     Kode_MK CHAR (12) NOT NULL , 
     Nama_MK VARCHAR (30) NOT NULL , 
     SKS CHAR (1) NOT NULL , 
     Semester CHAR (1) NOT NULL , 
     Praktikum VARCHAR (5) , 
     Dosen_NIP CHAR (18) NOT NULL 
    )
;

ALTER TABLE Mata_Kuliah ADD CONSTRAINT Mata_Kuliah_PK PRIMARY KEY (Kode_MK)
;

CREATE TABLE Mata_Kuliah_Peminatan 
    (
     Kode_MK CHAR (12) NOT NULL , 
     MK_Prasayarat VARCHAR (30) 
    )
;

ALTER TABLE Mata_Kuliah_Peminatan ADD CONSTRAINT Mata_Kuliah_Peminatan_PK PRIMARY KEY (Kode_MK)
;

CREATE TABLE Mata_Kuliah_Wajib 
    (
     Kode_MK CHAR (12) NOT NULL 
    )
;

ALTER TABLE Mata_Kuliah_Wajib ADD CONSTRAINT Mata_Kuliah_Wajib_PK PRIMARY KEY (Kode_MK)
;

CREATE TABLE Prodi 
    (
     Kode_Prodi CHAR (5) NOT NULL , 
     Nama_Prodi VARCHAR (30) NOT NULL , 
     Fakultas_Kode_Fakultas CHAR (2) NOT NULL 
    )
;

ALTER TABLE Prodi ADD CONSTRAINT Prodi_PK PRIMARY KEY (Kode_Prodi)
;

ALTER TABLE Dosen
    ADD CONSTRAINT Dosen_Dosen_FK FOREIGN KEY
    ( 
     Dosen_NIP
    ) 
    REFERENCES Dosen 
    ( 
     NIP
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE Dosen
    ADD CONSTRAINT Dosen_Prodi_FK FOREIGN KEY
    ( 
     Prodi_Kode_Prodi
    ) 
    REFERENCES Prodi 
    ( 
     Kode_Prodi
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE KRS
    ADD CONSTRAINT KRS_Mahasiswa_FK FOREIGN KEY
    ( 
     Mahasiswa_NIM
    ) 
    REFERENCES Mahasiswa 
    ( 
     NIM
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE KRS
    ADD CONSTRAINT KRS_Mata_Kuliah_FK FOREIGN KEY
    ( 
     Mata_Kuliah_Kode_MK
    ) 
    REFERENCES Mata_Kuliah 
    ( 
     Kode_MK
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE Mahasiswa
    ADD CONSTRAINT Mahasiswa_Prodi_FK FOREIGN KEY
    ( 
     Prodi_Kode_Prodi
    ) 
    REFERENCES Prodi 
    ( 
     Kode_Prodi
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE Mata_Kuliah
    ADD CONSTRAINT Mata_Kuliah_Dosen_FK FOREIGN KEY
    ( 
     Dosen_NIP
    ) 
    REFERENCES Dosen 
    ( 
     NIP
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

ALTER TABLE Mata_Kuliah_Peminatan
    ADD CONSTRAINT Mata_Kuliah_Peminatan_Mata_Kuliah_FK FOREIGN KEY
    ( 
     Kode_MK
    ) 
    REFERENCES Mata_Kuliah 
    ( 
     Kode_MK
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE Mata_Kuliah_Wajib
    ADD CONSTRAINT Mata_Kuliah_Wajib_Mata_Kuliah_FK FOREIGN KEY
    ( 
     Kode_MK
    ) 
    REFERENCES Mata_Kuliah 
    ( 
     Kode_MK
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE Prodi
    ADD CONSTRAINT Prodi_Fakultas_FK FOREIGN KEY
    ( 
     Fakultas_Kode_Fakultas
    ) 
    REFERENCES Fakultas 
    ( 
     Kode_Fakultas
    )
    ON DELETE CASCADE
    ON UPDATE NO ACTION
;

CREATE TRIGGER FNM_KRS 
NO CASCADE BEFORE UPDATE OF Mahasiswa_NIM,Mata_Kuliah_Kode_MK 
ON KRS 
FOR EACH ROW MODE DB2SQL 
BEGIN ATOMIC 
  signal SQLSTATE '85003' ('Non Transferable FK constraint  on table KRS is violated'); 
END 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE ALIAS                             0
-- CREATE BUFFERPOOL                        0
-- CREATE DATABASE                          0
-- CREATE DISTINCT TYPE                     0
-- CREATE INSTANCE                          0
-- CREATE NODE GROUP                        0
-- CREATE TABLESPACE                        0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
